services:
  - type: web
    name: loan-sales-prediction
    runtime: python
    plan: free
    buildCommand: "./render-build.sh"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
